# Generated by Django 2.1.3 on 2018-12-24 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.PositiveSmallIntegerField()),
                ('r1', models.CharField(max_length=10)),
                ('r2', models.CharField(max_length=10)),
                ('r3', models.CharField(max_length=10)),
                ('r4', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='br.Reading'),
        ),
    ]
