# Generated by Django 2.1.3 on 2018-12-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0002_auto_20181224_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='r3',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='r4',
        ),
        migrations.AddField(
            model_name='reading',
            name='reading',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
