# Generated by Django 2.1.3 on 2018-12-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0003_auto_20181224_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='reading',
            new_name='r',
        ),
    ]
