# Generated by Django 2.1.3 on 2019-01-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0005_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='r0',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='r1',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='r2',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='r3',
        ),
        migrations.AddField(
            model_name='progress',
            name='reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='br.Reading'),
        ),
        migrations.AddField(
            model_name='progress',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
