# Generated by Django 2.1.3 on 2019-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0007_notice_readinggroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='code',
            field=models.CharField(default="''.join(random.SystemRandom().choice('abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for i in range(6))", max_length=6),
        ),
    ]
