# Generated by Django 2.1.3 on 2019-01-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0008_auto_20190110_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='code',
            field=models.CharField(default='2d$4f5', max_length=6),
        ),
    ]
