# Generated by Django 2.1.3 on 2019-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0009_auto_20190110_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
