# Generated by Django 2.1.4 on 2019-01-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
