# Generated by Django 2.1.3 on 2018-12-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile_bible_ver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bible_ver',
            field=models.CharField(choices=[('ASV', 'The Holy Bible, American Standard Version Bible'), ('engDRA', 'Douay-Rheims American 1899 The Holy Bible in English, Douay-Rheims American Edition of 1899, translated from the Latin Vulgate'), ('enggnv', 'Geneva Bible common'), ('enKJVe', 'King James (Authorised) Version Ecumenical'), ('enKJVp', 'King James (Authorised) Version Protestant'), ('engojp', 'JPS TaNaKH 1917 Jewish'), ('engRV', 'Revised Version 1885 Interconfessional'), ('FBVNT', 'Free Bible Version New Testament with Psalms New edition of FBV NT that now includes Psalms'), ('GNT', 'Good News Translation Protestant Bible'), ('GNTD', 'Good News Translation (US Version) Catholic Interconfessional Bible'), ('GNTDSI', 'Good News Translation (US Version) Book of Sirach Good News Translation (US Version) Book of Sirah'), ('T4T', 'Translation for Translators common'), ('WEBE', 'World English Bible Ecumenical'), ('WEBC', 'World English Bible Catholic'), ('WEBO', 'World English Bible Orthodox'), ('WEBP', 'World English Bible Protestant'), ('WEBBEE', 'World English Bible British Edition Ecumenical'), ('WEBBEC', 'World English Bible British Edition Catholic'), ('WEBBEO', 'World English Bible British Edition Orthodox'), ('WEBBEP', 'World English Bible British Edition Protestant'), ('WMB', 'World Messianic Bible Messianic'), ('WMBBEM', 'World Messianic Bible British Edition Messianic')], default='WEBP', max_length=6),
        ),
    ]
